//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBlog01.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        /* [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
         public Articles()
         {
             this.Bookmarks = new HashSet<Bookmarks>();
         }*/

        public int artcle_id { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public string descrpt { get; set; }
        public string author { get; set; }
        public Nullable<int> rating { get; set; }
        public string comm_title { get; set; }
        public string image { get; set; }
    
        /*public virtual Users Users { get; set; }
        public virtual Category Category { get; set; }
        public virtual Comments Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmarks> Bookmarks { get; set; }*/
    }
}
