//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBlog01.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmarks
    {
        public int bm_id { get; set; }
        public string arttitle { get; set; }
        public string usern { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Articles Articles { get; set; }
    }
}
